on:
  push:
    branches:
      - develop

name: Ejecutar test en cada push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB: ${{secrets.DOCKER_HUB}}
      DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}

    steps:
      - name: Clonar y checkout de la rama actual
        uses: actions/checkout@v1
      - name: Instalar dependecias
        run: npm install
      - name: Ejecutar test
        run: npm test
      - name: echos
        run: 
          echo $DOCKER_HUB
          docker login -u $DOCKER_HUB -p $DOCKER_HUB_PASSWORD
