on:
  push:
    branches:
      - develop

name: Just develop and every push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB: ${{secrets.DOCKER_HUB}}
      DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      VERSION: 'dev'

    steps:
      - name: clone and checkout
        uses: actions/checkout@v1
      - name: install dependencies
        run: npm install
      - name: run test
        run: npm test
      - name: build image
        run: docker build . -t diademuertos/tdd_acctions:$VERSION
      - name: login docker hub
        run: docker login -u $DOCKER_HUB -p $DOCKER_HUB_PASSWORD
      - name: push image to docker hub repository
        run: docker push diademuertos/tdd_acctions:$VERSION
      - name: if test
        if: github.ref == 'develop'
        run: DONE
      - name: github.ref
        run: echo ${{github.ref}}
