on:
  push:
    branches:
      - develop
      - master

name: Just develop and every push

jobs:
  build:
    runs-on: ubuntu-latest
    node-version: '8.10.0'
    env:
      DOCKER_HUB: ${{secrets.DOCKER_HUB}}
      DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      VERSION_DEV: 'dev'
      VERSION_PRO: 'latest'

    steps:
      - name: clone and checkout
        uses: actions/checkout@v1
      - name: install dependencies
        run: npm install
      - name: run test
        run: npm test
      - name: build dev image
        if: contains(github.ref, 'develop')
        run: |
          export VERSION=$VERSION_DEV
          docker build . -t diademuertos/tdd_acctions:$VERSION
      - name: build pro image
        if: contains(github.ref, 'master')
        run: |
          export VERSION=$VERSION_PRO
          docker build . -t diademuertos/tdd_acctions:$VERSION
      - name: login docker hub
        run: docker login -u $DOCKER_HUB -p $DOCKER_HUB_PASSWORD
      - name: push image to docker hub repository
        run: docker push diademuertos/tdd_acctions
      - name: create greeting file
        run: echo Hello world > greeting.txt
      - name: upload greeting file
        uses: actions/upload-artifact@v1
        with:
          name: greeting
          path: greeting.txt
  job1:
    name: create file
    runs-on: ubuntu-latest

    steps:
      - name: create
        run: echo 8 + 1 > output.txt
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: output.txt

  job2:
    name: display file
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: download
        uses: actions/download-artifact@v1
        with:
          name: output
      - name: display
        run: cat output/output.txt
